### ISSUE TITLE
If I want to do something in else, is there a way to do it now?

### ISSUE THREAD

**Issue by rendaoer** [benfrankel/tiny_bail#2]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/2e5513a0-777a-452a-82f4-50c795adcefd">

**Comment by benfrankel** [comment]
Currently the only thing the macros can do in the failure case is log a warning.

I want to say that supporting this would be out of scope. However, you do lose the warning on bail when you're forced to use a `let-else` instead of one of the macros, so I can see the value in it.

**Comment by benfrankel** [comment]
Actually... this is currently possible, technically:

```rust
let distance = or_return!(
    {
        *hover_point = HoverPoint::None;
    },
    ray.intersect_plane(map.translation(), ...),
);
```

This abuses the optional "return value" argument by returning an expression that does some things before yielding the value to be returned (`()` in this case).
